# 特徴量リストの定義
FEATURE:
  "FEATURE_LIST":
    [
    # '年月日',
    '列車番号',
    # '停車駅名',
    # 'フェンダー部分_東京方向_',
    # '台車部分',
    # 'フェンダー部分_金沢方向_',
    # '合計',
    # '回送列車フラグ',
    # '停車時刻',
    # '金沢',
    # '新高岡',
    # '富山',
    # '黒部宇奈月温泉',
    # '糸魚川',
    # '上越妙高',
    # '飯山',
    # '長野',
    '金沢着雪ゼロ列車フラグ',
    ]

  "CATEGORICAL_COLS":
    [
    '列車番号',
    '金沢着雪ゼロ列車フラグ'
    ]


# ==========================================
# 気象データ
# ==========================================
WEATHER_FEATURE:
  locations:
    - 富山
    - 糸魚川
    - 金沢

  variables:
    - 気温
    - 降水量
    - 降雪
    - 積雪
    - 日照時間_時間_
    - 風速_m_s_
    - 風向
    - 日射量_MJ_m2_
    - 現地気圧_hPa_
    - 海面気圧_hPa_
    - 相対湿度_%_
    - 蒸気圧_hPa_
    - 雲量_10分比_
    - 露点温度_℃_

  hours:
    - "1_00"
    - "2_00"
    - "3_00"
    - "4_00"
    - "5_00"
    - "6_00"
    - "7_00"
    - "8_00"
    - "9_00"
    - "10_00"
    - "11_00"
    - "12_00"
    - "13_00"
    - "14_00"
    - "15_00"
    - "16_00"
    - "17_00"
    - "18_00"
    - "19_00"
    - "20_00"
    - "21_00"
    - "22_00"
    - "23_00"
    - "0_00"


WEATHER_CATEGORY:
  "WEATHER_CATEGORY_LIST":
    [
    '風向',
    ]


# ==========================================
# 積雪計データ
# ==========================================
SNOW_FEATURE:
  locations:
    - 富山野々上
    # 実際の「地域名」の値に合わせて追加
    # - ○○
    # - ○○

  variables:
    - 積雪深_軌道_
    - 積雪深_側溝_
    - 積雪深_軌道A_
    - 積雪深_軌道B_

  statistics:
    - mean
    - max
    - min

  time_zones:
    - "0-6"
    - "6-12"
    - "12-18"
    - "18-24"


# 積雪計のカテゴリカル変数
SNOW_CATEGORY:
  "SNOW_CATEGORY_LIST":
    []


# ==========================================
# LightGBM のパラメータ設定
# ==========================================
MODEL_PARAMS:
  "objective": "regression"
  "metric": "rmse"
  "alpha": 0.8
  "boosting_type": "gbdt"
  "min_data_in_leaf": 50
  "learning_rate": 0.05
  "num_leaves": 64
  "max_depth": -1
  "feature_fraction": 0.8
  "bagging_fraction": 0.8
  "bagging_freq": 1
  "verbosity": -1