# 特徴量リストの定義
FEATURE:
  "FEATURE_LIST":
    [
    # '年月日',
    '列車番号',
    '停車駅名',
    # 'フェンダー部分(東京方向)',
    # '台車部分',
    # 'フェンダー部分(金沢方向)',
    # '合計',
    # '回送列車フラグ',
    # '停車時刻',
    # '金沢',
    # '新高岡',
    # '富山',
    # '黒部宇奈月温泉',
    # '糸魚川',
    # '上越妙高',
    # '飯山',
    # '長野',
    # '金沢着雪ゼロ列車フラグ'
      ]
  "CATEGORICAL_COLS":
   [
    # '年月日', 
    '列車番号',
    '停車駅名',
  #  '金沢着雪ゼロ列車フラグ'
   ]

# LightGBM のパラメータ設定
MODEL_PARAMS:
    "objective": "regression"
    "metric": "rmse"
    "alpha": 0.8
    'boosting_type': 'gbdt'
    "min_data_in_leaf": 50
    "learning_rate": 0.05
    "num_leaves": 64
    "max_depth": -1
    "feature_fraction": 0.8
    "bagging_fraction": 0.8
    "bagging_freq": 1
    "verbosity": -1